import Head from "next/head";
import { useEffect, useState } from "react";
import { useRouter } from "next/router";
import jwt from "jsonwebtoken";
import s from "../styles/Landing.module.scss";
import CarouselComplete from "../src/components/Carousel/Carousel";

import axios from "axios";

export default function Home() {
  const [isValidated, setIsValidated] = useState(false);
  const router = useRouter();

  useEffect(() => {
    const redirectByRole = async () => {
      const token = window.localStorage.getItem("token");
      const today = new Date();
      const decodedToken = jwt.decode(token, { complete: true });
      if (!token) {
        setIsValidated(true);
        router.push("/");
        return;
      }

      if (decodedToken.payload.exp * 1000 < today.getTime()) {
        window.localStorage.removeItem("token");
        setIsValidated(true);
        router.push("/");
        return;
      }
      let options = {
        headers: {
          "Content-Type": "application/json;charset=UTF-8",
          "Access-Control-Allow-Origin": "*",
          auth: token,
        },
      };
      const { data } = await axios.get(
        "https://alba-app.us-south.cf.appdomain.cloud/users/profile",
        options
      );
      data.user.role.map((userRole) => {
        console.log(userRole);
        if (userRole === "admin") {
          router.push("/admin");
          setIsValidated(true);
          return;
        } else if (userRole === "partner") {
          //ruta de los partners
          //setIsValidated(true);
          setIsValidated(true);
          return;
        } else if (!userRole || userRole === "user") {
          router.push("/");
          setIsValidated(true);
          return;
        }
      });
      setIsValidated(true);
    };
    redirectByRole();
    return () => {
      setIsValidated(false);
    };
  }, []);

  return (
    <>
      {!isValidated ? (
        <div className="container container-fluid ">
          <h1>Loading...</h1>
        </div>
      ) : (
        <div>
          <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>

          <div className={s.body}>
            <div className={s.video}></div>
            <CarouselComplete className={s.carousel} />
            <div className={s.cursos}></div>
            <div className={s.suscriptions}>
              <h1>SUSCRIPCIONES</h1>
            </div>
            <div>
              <div>asdas</div>
              <div>asdas</div>
            </div>
          </div>
        </div>
      )}
    </>
  );
}
